---
# video_input: nvcamerasrc ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720,format=(string)I420, framerate=(fraction)5/1 ! nvvidconv flip-method=2 ! video/x-raw, width=(int)1280, height=(int)720, format=(string)BGRx ! videoconvert ! appsink             # Input Must be OpenCV readable 
video_input: /dev/video1    # Input Must be OpenCV readable 
visualize: True             # Disable for performance increase
max_frames: 500             # only used if visualize==False
width: 300                  # 300x300 is used by SSD_Mobilenet -> highest fps
height: 300
fps_interval: 5             # Intervall [s] to print fps in console
memory_fraction: 0.3        # per_process_gpu_memory_fraction
allow_memory_growth: True   # restart python to apply changes on memory usage
det_interval: 75            # intervall [frames] to print detections to console
det_th: 0.5                 # detection threshold for det_intervall

# Change only if you use another model
model_name: 'ssd_mobilenet_v11_coco'
model_path: '/home/nvidia/AutonomousTju/src/ssd_mobilenet/models/ssd_mobilenet_v11_coco/frozen_inference_graph.pb'
label_path: '/home/nvidia/AutonomousTju/src/ssd_mobilenet/object_detection/data/mscoco_label_map.pbtxt'
num_classes: 90
